# Generated by Django 6.0.1 on 2026-01-21 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('ETC', 'ETC'), ('CRYPTO', 'Crypto')], default='STOCK', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIV', 'Dividend')], max_length=4)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('div_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
