# Generated by Django 6.0.1 on 2026-01-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_asset_data_symbol_alter_asset_ticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_symbol',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='portfolio.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'date'], name='portfolio_p_asset_i_4e1a27_idx'), models.Index(fields=['date'], name='portfolio_p_date_402168_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='unique_asset_date')],
            },
        ),
    ]
