# Generated by Codex on 2026-02-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_asset_data_symbol_pricepoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="portfolio.user",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="data_symbol",
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveConstraint(
            model_name="asset",
            name="unique_ticker_exchange",
        ),
    ]
