# Generated by Codex on 2026-02-04

import django.db.models.deletion
from django.db import migrations, models


def split_assets_per_user(apps, schema_editor):
    Asset = apps.get_model("portfolio", "Asset")
    Transaction = apps.get_model("portfolio", "Transaction")
    User = apps.get_model("portfolio", "User")

    fallback_user = User.objects.order_by("id").first()
    fallback_user_id = fallback_user.id if fallback_user else None

    for asset in Asset.objects.all().order_by("id"):
        user_ids = list(
            Transaction.objects.filter(asset_id=asset.id)
            .values_list("user_id", flat=True)
            .distinct()
            .order_by("user_id")
        )

        if not user_ids:
            if fallback_user_id is None:
                # Orphan asset with no available owner; remove to keep user-specific integrity.
                asset.delete()
                continue
            asset.user_id = fallback_user_id
            asset.save(update_fields=["user"])
            continue

        primary_user_id = user_ids[0]
        asset.user_id = primary_user_id
        asset.save(update_fields=["user"])

        # Duplicate this asset for other users who previously shared it.
        for user_id in user_ids[1:]:
            clone = Asset.objects.create(
                user_id=user_id,
                ticker=asset.ticker,
                name=asset.name,
                asset_type=asset.asset_type,
                currency=asset.currency,
                exchange=asset.exchange,
                data_symbol=asset.data_symbol,
            )
            Transaction.objects.filter(asset_id=asset.id, user_id=user_id).update(asset_id=clone.id)


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_asset_user_scope_prep"),
    ]

    operations = [
        migrations.RunPython(split_assets_per_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="portfolio.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("user", "ticker", "exchange"),
                name="unique_user_ticker_exchange",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("user", "data_symbol"),
                name="unique_user_data_symbol",
            ),
        ),
    ]
