# Generated by Django 6.0.1 on 2026-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_asset_user_scope_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='short_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
