# Generated by Django 6.0.1 on 2026-04-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_asset_short_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "timestamp"], name="portfolio_t_user_id_cacdcc_idx"
            ),
        ),
    ]
