# Generated by Django 6.0.1 on 2026-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_transaction_user_timestamp_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="prices_covered_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="prices_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
